#ifndef DOG_SOOTHER_UART_CMD_H_
#define DOG_SOOTHER_UART_CMD_H_

/* 帧 msg_type */
#define DS_UART_MSG_REQ 0x01
#define DS_UART_MSG_RSP 0x02
#define DS_UART_MSG_EVT 0x03
#define DS_UART_PROTO_VER 0x01

/* MCU -> SOC 请求 cmdId（须与 vendor/ble_egg_anfu/app_uart.h 一致） */
#define DS_CMD_POWER_CTRL 0x10
#define DS_CMD_STATUS_GET 0x11
#define DS_CMD_VOLUME_SET 0x12
#define DS_CMD_OWNER_REC_START 0x20
#define DS_CMD_OWNER_REC_STOP 0x21
#define DS_CMD_OWNER_REC_PLAY 0x22
#define DS_CMD_OWNER_REC_DELETE 0x23
#define DS_CMD_OWNER_REC_INFO_GET 0x24
#define DS_CMD_OWNER_REC_PLAY_STOP 0x25
#define DS_CMD_CALM_MUSIC_PLAY 0x26
#define DS_CMD_CALM_MUSIC_PLAY_STOP 0x27
#define DS_CMD_CALM_MODE_SET 0x30
#define DS_CMD_CALM_STRATEGY_SET 0x31
#define DS_CMD_TIME_SET 0x32
#define DS_CMD_CALM_STRATEGY_GET 0x33
#define DS_CMD_LOG_PULL 0x40
#define DS_CMD_CALM_RECORD_GET 0x41
#define DS_CMD_CALM_RECORD_DELETE 0x42
#define DS_CMD_FACTORY_RESET 0x50
#define DS_CMD_BT_LINK_NOTIFY 0x60

/* SOC -> MCU 事件 cmdId */
#define DS_EVT_WORK_STATE 0x80
#define DS_EVT_BARK_DETECTED 0x81
#define DS_EVT_MEASURE_EXEC 0x82
#define DS_EVT_SESSION_RESULT 0x83
#define DS_EVT_OWNER_REC 0x84
#define DS_EVT_LOG_DATA 0x85
#define DS_EVT_ERROR 0x86
#define DS_EVT_HEARTBEAT 0x87

#endif /* DOG_SOOTHER_UART_CMD_H_ */
